### ISSUE TITLE
GOKZ replay bots get pulled down as if there is always an antibhop trigger under it

### ISSUE THREAD

**Issue by zealain** [KZGlobalTeam/gokz#130]
**[Original report](https://bitbucket.org/kztimerglobalteam/gokz/issue/130) by zer0.k (Bitbucket: [zer0k_z](https://bitbucket.org/zer0k_z), ).**

----------------------------------------

Sometimes using !replay, the bot will get pulled down before every jump \(except bhops\) and sounds like they got pulled down by an antibhop trigger. This will get fixed by reloading the map or the server.

‌

**Comment by zer0k-z** [comment]
Apparently it is still happening sometimes...
