### ISSUE TITLE
Jumptop replay bot spawns at 0,0,0 and doesn't move

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#236]
Jumptop replay bot spawns at 0,0,0 and doesn't move
Sometimes the replay plays correctly
Normal bot works fine
Nothing in the error logs

Video: https://streamable.com/9plvj3

**Comment by Szwagi** [comment]
Another example from discord, this time a run replay: https://streamable.com/0ceafr

**Comment by AndrewRailton** [comment]
I'm experiencing this as well with a normal nub bot. nub bot 2 is working though, both were created after the 3.0 update. 
Pre 3.0 replays work fine after moving them to the _runs folder. 

I can provide the replay files if that will help troubleshoot.
