### ISSUE TITLE
Replay bots get assigned a rank clantag

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#237]
Replay bots get [KZT New] as their clantag

![image](https://user-images.githubusercontent.com/12988954/158009705-ea27e06d-6b15-4b03-b5a9-61fe6cb0aeac.png)

**Comment by Ferexx** [comment]
This isn't happening on my server. Was it like this on the server start, or after a run, or something?

**Comment by Szwagi** [comment]
It was after the map started, after watching a replay it went back to the REPLAY clantag.

**Comment by zealain** [comment]
I've added some more checks, so should hopefully be fixed? Please reopen if it still happens.
