### ISSUE TITLE
Chinese translations of the word "Bonus" update

### ISSUE THREAD

**Issue by LaplaceTor** [KZGlobalTeam/gokz#247]
gokz-common.phrases.txt 
- _line 22_
-   		"chi"		"{grey}Bonus'{default}{1}{grey}'不存在"

gokz-core.phrases.txt
- _line 20_
- 		"chi"		"{lime}{1} {grey}在{bluegrey}Bonus{2}{grey}以{yellow}读点{default}方式完成地图,用时{3}{grey} [{purple}{4}{grey}]"
- _line 28_
-  		"chi"		"{lime}{1} {grey}在{bluegrey}Bonus{2}{grey}以{yellow}裸跳{default}方式完成地图,用时{3}{grey} [{purple}{4}{grey}]"
- _line 178_
- 		"chi"		"{grey}找不到 {bluegrey}Bonus {1} {grey}的起点"
- _line 188_
- 		"chi"		"{grey}找不到 {bluegrey}Bonus {1} {grey}的终点"

gokz-global.phrases.txt
- _line 32_
- 		"chi"		"{lime}{1}{grey} 现在成为了{bluegrey}Bonus{3}{red}全球前{grey}[{purple}{4}{grey}名的读点纪录中的第{default}{2}{grey}名"
- _line 40_
- 		"chi"		"{lime}{1}{grey} 现在成为了{bluegrey}Bonus{3}{darkred}全球前{grey}[{purple}{4}{grey}名的第#{default}{2}{grey}名"
- _line 64_
- 		"chi"		"{lime}{1}{grey} 刷新了{bluegrey}Bonus {2} {red}的存点世界纪录: {grey}[{purple}{3}{grey}]"
- _line 72_
- 		"chi"		"{lime}{1}{grey} 刷新了{bluegrey}Bonus {2} {red}的裸跳世界纪录: {grey}[{purple}{3}{grey}]"
- _line 116_
- 		"chi"		"{grey}地图 {default}{1}{bluegrey} Bonus {2} {grey}的世界纪录:[{purple}{3}{grey}]"
- _line 217_
- 		"chi"		"地图世界纪录\n \n地图 - {1} (Bonus {2} )\n "
- _line 240_
- 		"chi"		"地图世界纪录\n \n地图 - {1} (Bonus {2})\n模式 - {3}\n "
- _line 264_
- 		"chi"		"地图 {1} 世界排名\n \n地图 - {2} (Bonus {3})\n模式 - {4}\n "

gokz-localranks.phrases.txt
- _line 28_
- 		"chi"		"{default}{1} {bluegrey}Bonus {2}{grey}未找到."
- _line 78_
- 		"chi"		"{lime}{1}{grey} 刷新了 {bluegrey}Bonus {2} 的 {yellow}存点纪录{grey}: [{purple}{3}{grey}]"
- _line 86_
- 		"chi"		"{lime}{1}{grey} 刷新了 {bluegrey}Bonus {2} 的 {yellow}裸跳纪录{grey}: [{purple}{3}{grey}]"
- _line 94_
- 		"chi"		"{lime}{1}{grey} 刷新了 {bluegrey}Bonus {2} 的 {yellow}存点/裸跳纪录{grey}: [{purple}{3}{grey}]"
- _line 150_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{yellow}存点{grey}方式完成地图,完成时长 {default}{3} {grey}[第{default}{4}{grey}名/共{default}{5}{grey}人完成地图] [{purple}{6}{grey}]"
- _line 158_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{yellow}存点{grey}方式完成地图,完成时长{default}{3} {grey}(比个人记录{green}快了{4}{grey}) {grey}[第{default}{5}{grey}名/共{default}{6}{grey}人完成地图] [{purple}{7}{grey}]"
- _line 166_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{yellow}存点{grey}方式完成地图,完成时长{default}{3} {grey}(比个人记录{green}慢了{4}{grey}) {grey}[第{default}{5}{grey}名/共{default}{6}{grey}人完成地图] [{purple}{7}{grey}]"
- _line 174_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{blue}裸跳{grey}方式完成地图,完成时长{default}{3} {grey}[第{default}{4}{grey}名/共{default}{5}{grey}人完成地图] [{purple}{6}{grey}]"
- _line 182_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{blue}裸跳{grey}方式完成地图,完成时长{default}{3} {grey}(比个人记录{green}快了{4}{grey}) {grey}[第{default}{5}{grey}名/共{default}{6}{grey}人完成地图] [{purple}{7}{grey}]"
- _line 190_
- 		"chi"		"{lime}{1}{grey} 在 {bluegrey}Bonus {2} {grey}以{blue}裸跳{grey}方式完成地图,完成时长{default}{3} {grey}(比个人记录{green}慢了{4}{grey}) {grey}[第{default}{5}{grey}名/共{default}{6}{grey}人完成地图] [{purple}{7}{grey}]"
- _line 206_
- 		"chi"		"{lime}{1}{grey} 在地图{default}{2} {bluegrey}Bonus {3} {grey}上的记录 [{purple}{4}{grey}]"
- _line 258_
- 		"chi"		"{grey}地图{default}{1}{bluegrey}Bonus {2} {grey}的服务器最快纪录[{purple}{3}{grey}]"
- _line 316_
- 		"chi"		"{grey}服务器{default}{1}{bluegrey}Bonus {2} {grey}的平均完成时间: {grey}[{purple}{3}{grey}]"
- _line 346_
- 		"chi"		"{lime}{1}{grey} 完成地图进度: 存点完成{default}{2}{grey}/{default}{3}{grey}张,{blue}裸跳{grey}完成{default}{4}{grey}/{default}{5}{grey}张；Bonus地图读点完成{default}{6}{grey}/{default}{7}{grey}张,{blue}裸跳{grey}完成{default}{8}{grey}/{default}{9}{grey}张. [{purple}{10}{grey}]"
- _line 409_
- 		"chi"		"Bonus 排行\n \n地图 - {1} (Bonus {2})\n \n选择一个模式 "
- _line 432_
- 		"chi"		"Bonus 排行\n \n地图 - {1} (Bonus {2})\n模式 - {3}\n "
- _line 471_
- 		"chi"		"服务器 {2} 前{1}\n \n地图 - {3} (Bonus {4})\n模式 - {5}\n "

gokz-saveloc.phrases.txt
- _line 130_
- 		"chi"		"{orchid}SaveLoc {grey}- {lime}{1} {grey}在{bluegrey}Bonus {2} {grey}以{yellow}读点{default}方式完成地图,用时{3}{grey} [{purple}{4}{grey}]"
- _line 138_
- 		"chi"		"{orchid}SaveLoc {grey}- {lime}{1} {grey}在{bluegrey}Bonus {2} {grey}以{yellow}裸跳{default}方式完成地图,用时{3}{grey} [{purple}{4}{grey}]"

gokz-tips-localranks.phrases.txt
- _line 27_
-		"chi"		"{grey}聊天框中输入 {default}!bwr <bonus>{grey}或者{default}!bmaptop <bonus>{grey}查看Bonus地图的记录"

Others  Chinese Translations update will pull request after I have time to do it

**Comment by zealain** [comment]
It's kinda awkward to copy all of those manually line by line from an issue. Please do make a pull request instead though! The chinese translation is indeed pretty outdated.
