### ISSUE TITLE
!profile stops working when VIP or ADMIN tags used

### ISSUE THREAD

**Issue by walliski** [KZGlobalTeam/gokz#256]
Steps to reproduce:
1. Set ADMIN tag to show
2. Rejoin server
3. do `!profile`

Expected to happen: I can see the profile menu.
What happens? Nothing.

Workaround: Set "Rank" to show, and it will work after that with all tags.

Tested on 3.0.3 & 3.0.5.

Stack trace from 3.0.5:
```
L 03/17/2022 - 23:03:33: [SM] Exception reported: Array index out-of-bounds (index -1, limit 23)
L 03/17/2022 - 23:03:33: [SM] Blaming: gokz-profile.smx
L 03/17/2022 - 23:03:33: [SM] Call stack trace:
L 03/17/2022 - 23:03:33: [SM]   [1] Line 116, gokz-profile/profile.sp::ProfileMenuAddItems
L 03/17/2022 - 23:03:33: [SM]   [2] Line 36, gokz-profile/profile.sp::ShowProfile
L 03/17/2022 - 23:03:33: [SM]   [3] Line 271, gokz-profile.sp::CommandProfile
```

**Comment by walliski** [comment]
Early return in https://github.com/KZGlobalTeam/gokz/blob/master/addons/sourcemod/scripting/gokz-profile.sp#L192 I guess, which prevents the ranks from being populated. Should be fine to just move the calculation before actually setting the tags to always run it? 🤔

**Comment by zealain** [comment]
Fixed in the next version.
