### ISSUE TITLE
Replays are getting overwritten with corrupted data

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#257]
Replays of runs that are not the server record are being written as the replay, with no replay data.

In the most recent occurrence, a 10:32 kz_oloramasa KZT NUB replay overwrote a 3:33 NUB replay with no replay data, the header is in tact.
The replay create date is 2 seconds older than the run entry in the database, so it definitely happens after the end timer.

**Comment by walliski** [comment]
Was this on 3.0.5?

**Comment by Szwagi** [comment]
> Was this on 3.0.5?

I just checked and it's on 3.0.3, for some reason I thought 3.0.4 so only took a look at the 3.0.5 changelogs before posting the issue.
If it's meant to be fixed in 3.0.4+, close the issue and I'll reopen if this comes up again.

**Comment by walliski** [comment]
Not sure about this specific one, but at least there should be some fixes to the recordings in 3.0.4, so it might fix your issue also 🤔

**Comment by zealain** [comment]
I hope it's fixed with the new version, but I'm not sure cause I can't exactly reproduce it. Please re-open the issue if it still happens with 3.0.5.
