### ISSUE TITLE
GOKZ 3.0 - Jumpstats | Broken LaH, LaJ abuse, landing bug

### ISSUE THREAD

**Issue by iwbf** [KZGlobalTeam/gokz#294]
# GOKZ 3.0 Jumpstats

**Note**
 - Version in the title means an issue that tested only on that version
 - Tested only on the **VNL** mode
 - Tested only on the **FEMBOY | KZ - Public 1 - 128tick [GLOBAL]** - `135.181.58.159:27046`

## Broken Ladder Hop | 3.0.2, 3.2.0
It is now impossible to register a ladder hop when you are above the ground, even if your height will be less than or equal to 57, which was fixed around 10/29/2020 for GOKZ 2.11 and can only be reproduced in GOKZ < 2.11 and >= 3.0. Also the ladder hop stats in the chat shows (sometimes not) an extremely random parameter `C`, which differs from console crouched parameter.

## Ladder Jump Abuse | 2.7.2, 3.0.2
Quick introduction to [Ladder Glide](https://youtu.be/BhSIxCB7-QI?t=9) by [RedMooN](https://www.youtube.com/channel/UC9SFnSwPeEH4du-Ybw4Mrww)

GOKZ register ladder glide as ladder jump for some types of ladder. GOKZ doesn't have any checks for it as it is kind of a new technique in kreedz community. I have found so far only one place where this can be done - `de_lake` and the ladder on the pond.

## Landing Bug | 3.0.2
RnG and hard to reproduce bug. I (and not only me) had this bug only on the LJ blocks.

 - [Record from GOKZ pov demo](https://youtu.be/fjIlDYrlSr4)
 - [Download GOKZ pov demo](https://anonfiles.com/Nbz3D5R3xe/244.8_-_bug_dem) - `51000 tick`

```
\u0000 jumped 244.8975 units with a Long Jump
VNL | 240 Block | 4.64 Edge | 7 Strafes | 88% Sync | 250.00 Pre | 324.59 Max | 0 W | 0 OL | 0 DA | 9.6 Deviation | 29.1° Width | 57.0 Height | 100 Airtime | 0.0 Offset | 5 Crouched
  #.  Sync      Gain      Loss      Airtime   Width     OL     DA     
  1.   88%      14.56      0.41      17%       38.3°     0      0
  2.  100%      17.81      0.00      32%       47.3°     0      0
  3.   85%      14.30      0.87      14%       37.7°     0      0
  4.   90%      11.66      1.08      11%       31.5°     0      0
  5.   84%      11.72      0.84      13%       28.1°     0      0
  6.   72%       7.75     281.74      11%       20.1°     0      0
  7.    0%       0.00     15.47       2%        0.6°     0      0

[GC] LJ: 244.8975 [Edge: 4.640 | Block: 240 | Pre: 250.00 | Max: 324.5 | Airpath: 1.0220 | Deviation: 9.551 | Height: 57.00 | Sync: 88.8 | Air: 99 | -W: ✓ | OL: 0 | DA: 0 | Jumpoff Angle: -12.0°]
 #.  Sync   Gain   Loss  Max   Air  OL  DA  AvgGain  Efficiency (avg & peak)
 1.  93.3  13.89   0.00  263.8  15   0   0  0.92     -3.25 ( 0.43)
 2.  96.7  17.69   0.41  281.1  31   0   0  0.57     -3.88 (-0.28)
 3.  93.3  14.07   0.00  295.2  15   0   0  0.93     -2.74 (-0.20)
 4.  91.6  12.66   0.87  307.0  12   0   0  1.05     -1.75 (-0.19)
 5.  83.3  10.99   1.08  316.9  12   0   0  0.91     -1.67 ( 1.20)
 6.  81.8   8.47   0.84  324.5  11   0   0  0.77     -2.20 ( 0.35)
 7.   0.0   0.00 289.52   50.6   3   0   0  0.00     54.32 ( 3.76)
 ```

**Comment by zer0k-z** [comment]
> Ladder Hop
Offset ladderhop is no longer valid, that's intended, see this PR: https://bitbucket.org/kztimerglobalteam/gokz/pull-requests/197
I can't seem to get the crouch indicator showing up in chat though, only in the speed panel for LAJ.

> LAJ abuse
I made a PR to fix it, hopefully. https://github.com/KZGlobalTeam/gokz/pull/297

> Landing Bug
From your pov demo, your takeoff position is `8052.709961 6836.056641`, your landing position is  `8062.355469 6623.406250`
Distance = `sqrt((8062.355469-8052.709961)**2+(6836.056641-6623.406250)**2) + 32 ~ 244.87`, so it seems fine to me...?
Unless you talk about the part where you lose all the speed at the end, that happens because you hit the front of the block.

**Comment by iwbf** [comment]
> Unless you talk about the part where you lose all the speed at the end, that happens because you hit the front of the block.

Yes, fine, thanks for the explanation

**Comment by iwbf** [comment]
> Landing Bug

Okay, I just realized why that started happening after the 3.0 release - #124
