### ISSUE TITLE
Add PRO version of menus

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#312]
Got a request to upstream a feature from my GOKZ fork. Creating this issue to not forget to do that, and to make sure zealain is onboard with the idea and if he wants any changes.

___Simple PRO Menu___
1. **Checkpoint**
2. **Teleport** _(Greyed out if in a run)_
3. **Pause**
4. **Restart** _(Greyed out if in a run above 20 seconds)_

___Advanced PRO Menu___
1. **Checkpoint**
2. **Teleport** _(Greyed out if in a run)_
4. **Prev CP** _(Greyed out if in a run)_
5. **Next CP** _(Greyed out if in a run)_
6. **Undo TP** _(Greyed out if in a run)_
7. **Pause**
9. **Restart** _(Greyed out if in a run above 20 seconds)_

___Commands___

- **!pro** - Toggles PRO menu on the currently selected menu style
- **!adv** - Toggles selected menu style and disables PRO menu

**Comment by walliski** [comment]
I do like the concept of blocking the menus. I often use the menu for pausing, and fatfingering the restart button in a run is really annoying.

I wonder if it would make more sense to add a confirmation menu for the restart button when using the pro menu though? Then you could tap "7, 1" to restart even when you are longer in the run, but it would prevent missclicks. I guess you could just use a sm_r bind instead though.
