### ISSUE TITLE
Replay bots missing smoothing/client prediction

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#335]
Bots are very "choppy", feels like the game runs at 30fps. 

It's caused by this commit: https://github.com/KZGlobalTeam/gokz/commit/8b28945abba71c4bb04724e73c103e2f1079b2b4
CreateFakeClient spawns different bots than the game spawns itself.

**Comment by Szwagi** [comment]
Also, bots hanging around in spec seemed to be intended and makes discovering the command easier for new players, so I'm not sure why that needed changing.

**Comment by walliski** [comment]
> Also, bots hanging around in spec seemed to be intended and makes discovering the command easier for new players, so I'm not sure why that needed changing.

Two benefits I see:
1. If you have a small server with few slots, you do not waste slots by having bots there all the time.
2. More than two people can watch replays at the same time.

Not really sure though if these two benefits are worth it, if there are negative aspects to be considered as well.

**Comment by zer0k-z** [comment]
Can confirm that 3.3.0 bots break movement interpolation.
