### ISSUE TITLE
Require stopped timer to change course

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#345]
Beginners get confused about bonuses placed in the middle of the map.
They usually click it thinking it's the end timer, get confused and continue running, only realizing at the end of the map what they've done.

A solution would be to force the player to type `!stop` when changing the course.
Players that intend on running the bonus will type `!b` or noclip to it in the majority of cases.

**Comment by zealain** [comment]
Fixed in 3.4.0
