### ISSUE TITLE
When playing multiplayer games, the character model is in a transparent state

### ISSUE THREAD

**Issue by Cinyan10** [KZGlobalTeam/gokz#357]
When playing multiplayer games, I see that others are in a transparent state. I am very uncomfortable about it. Can I change this option? If so, how should I change it?

**Comment by Sikarii** [comment]
As I mentioned in the [Discord](https://discord.gg/csgokz):
> Server owners have the option to change this with the `gokz_player_models_alpha` convar, it is not a player preference right now.

This could however be considered, it should not be too bad to support this in a player preference I believe?
CC @zealain

**Comment by Cinyan10** [comment]
thanks for your reply~
My thinking is that the server I'm building is more focused on the interaction with the player, and the characters being translucent will make that interaction less, and if I'm going to focus on breaking records, I can just use the ! Hide commands, these are my personal opinion






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 凌晨0:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KZGlobalTeam/gokz] When playing multiplayer games, the character model is in a transparent state (Issue #357)





 
‎正如我在‎‎Discord‎‎中提到的：‎
  
‎服务器所有者可以选择使用convar进行更改，现在这不是玩家的偏好。‎gokz_player_models_alpha
  
‎然而，这可以考虑，我相信在玩家偏好中支持这一点应该不会太糟糕吗？‎
 CC @zealain

**Comment by walliski** [comment]
#204 related

**Comment by zealain** [comment]
See #204
