### ISSUE TITLE
Missing materials in errorboxfixer

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/gokz#420]
There have been reports that downloading the GOKZ models and materials by themselves don't fix the error box.
After investigation I found that the GOKZ version does not include multiple materials, that are in the `materials/models/prop` directory in the KZTimer repo.

**Comment by walliski** [comment]
Related to https://github.com/KZGlobalTeam/gokz/pull/271#issuecomment-1076510811

It seems like I didn't quite get how things worked, and tried to be smart by not adding all items, which caused it to not work as it should. Probably should add all the "Switch" things also mentioned in the linked PR, of "unused" things. I suppose the switch is the weird looking button that is on walls to start timer 🤔

I can do another PR to fix this in the coming days.
