### ISSUE TITLE
Tpanglefix causing crashes on Linux when more than two players are online

### ISSUE THREAD

**Issue by Mooshua** [KZGlobalTeam/gokz#472]
**Reproduction**
 - Server with latest GOKZ installation
 - `sv_parallel_sendsnapshot` set to `1`
 - Connect two players (_not_ fake clients)
 - Observe immediate server crash

**Mitigation / Temporary Fixes**
 - Set `sv_parallel_sendsnapshot` to `0`
 - Disable gokz_tpanglefix.smx

**Crash Dumps**
https://crash.limetech.org/qsdrr375i7af
https://crash.limetech.org/p34vwqencu5g
https://crash.limetech.org/4kxdaqptbljh
https://crash.limetech.org/almxmp7dduy4
https://crash.limetech.org/hu2tahdovqcn
https://crash.limetech.org/ely7pmx7flx5
https://crash.limetech.org/ajleef3lq675
https://crash.limetech.org/slw2fvm5rso4
https://crash.limetech.org/xznep32mdzim
https://crash.limetech.org/b2ho6jz3vnp4
https://crash.limetech.org/oaddguub4gwb
https://crash.limetech.org/ymjdh7pq2g72
https://crash.limetech.org/gu476o3ozlmy

**Comment by walliski** [comment]
Is this fixed for you now @Mooshua after the latest update?

**Comment by Mooshua** [comment]
Yes, this is now resolved. Thanks!
